### ISSUE TITLE
Add support for hardcoding picture-based subtitles (VobSub and PGS)

### ISSUE THREAD

**Issue by deterenkelt** [deterenkelt/Nadeshiko#3]
#### TODO list

* [x] Clean `vf_string` composition. 
  * [x] Move subtitle preparation up, to argument checking.
  * [x] Introduce new variables for subtitle source format, rebuild checks based on whether they need extraction and conversion, whether they need to be overlaid.
  * [ ] (_maybe_) Separate font extraction.
* [x] Replace `-vf` with `-filter_complex`.
* [x] Divide subtitle addition between those that need `overlay` filter and those that do not.
* [ ] Determine whether overlaid subtitles still need timestamp correction.
* [ ] Add support for stream selection for audio track analogous to how it’s done for subtitles – it’s needed, because the official wiki [tells about bugs](https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo#Picture-basedsubtitles) appearing when audio track isn’t mapped. Thus when using overlay filter for subtitles, the `audio` parameter must be checked and mapped accordingly (`-map 0:a:$audio_track_id` added). Hmm, for now the default may be specified and can do… Something like `${audio:+ -map 0:a:0?}`.
* [ ] (_in the future_) External VobSub and PGS support.
